services:

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    ports:
      - "5050:80"
    volumes:
      - ./tmp-data/pgadmin:/var/lib/pgadmin
    command: sh -c "chown -R 5050:5050 tmp-data/pgadmin"
  
  digi-decor-db:
    image: postgres:14.4-bullseye
    env_file:
      - ./.postgresEnv
    ports:
      - "5434:5432"
    volumes:
      - ./tmp-data/digi-decor-db:/var/lib/postgresql/data
    depends_on:
      - pgadmin

  digi_decor:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
    links:
      - digi-decor-db
    depends_on:
      - digi-decor-db
      - minio
    command: bash -c "yarn install && bash ./docker/run.sh"

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./tmp-data/minio:/data
    environment:
      - MINIO_ROOT_USER=access-key
      - MINIO_ROOT_PASSWORD=secret-key
      - MINIO_REGION=us-west-2
    command: server /data --console-address ":9001"